import type { Metadata } from "next";
import "./globals.css";
import { ThirdwebProvider } from "thirdweb/react";
import { Header } from "@/components/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`font-mono min-h-screen`}
			>
				<ThirdwebProvider>
					<Header />
					<main>
						{children}
					</main>
				</ThirdwebProvider>
			</body>
		</html>
	);
}
